const Menu = [{
    id: 1,
    image:"./image/sandwich.jfif",
    name : "sandwich",
    category:"breakfast",
    description:"A sandwich is a food typically consisting of vegetables, sliced cheese or meat, placed on or between slices of bread,",
},
{
    id:2,
    image: "./image/egg.jfif",
    name: "Egg",
    category: "breakfast",
    description: "Eggs are a very good source of inexpensive, high- quality protein.",
},
{
        id: 3,
        image: "./image/oatmeal.jfif",
        name: "Oatmeal",
        category: "breakfast",
        description: "Oatmeal refers to a preparation of oats that have been dehusked, steamed and flattened. ",
    },
    {
        id: 4,
        image: "./image/sprouts-salad.jpg",
        name: "Sprouts salad",
        category: "breakfast",
        description: "The best sprouts for sandwiches and salads are vegetable seeds, particularly the brassica family.",
    },
    {
        id: 5,
        image: "./image/veg-biryani.jpg",
        name: " Veg Biryani",
        category: "lunch",
        description: "there are many varieties of biryani made in India. An authentic veg biryani is always slow cooked on dum.",
    },
    {
        id: 6,
        image: "./image/matar-paneer.jpg",
        name: "Matar paneer",
        category: "lunch",
        description: "spiced and creamy curry made with peas and cottage cheese.",
    },
    {
        id: 7,
        image: "./image/chole-masala.jpg",
        name: "Chana masala ",
        category: "lunch",
        description: "made with freshly powdered spices, onions, tomatoes, herbs making the chana taste like the ones you get on the streets of Delhi.",
    },
    {
        id: 8,
        image: "./image/egg-curry.jpg",
        name: "egg curry",
        category: "dinner",
        description: "this Indian vegetarian curry is loaded with lentils, spinach and creamy eggs. Use the roti to mop up all those delicious flavours",
    },
    {
        id: 9,
        image: "./image/curried-burger.jpeg",
        name: "Curried burger",
        category: "dinner",
        description: "Combine chickpeas, corn kernels and black beans to make a delicious vegan burger the whole family will enjoy",
    },
    {
        id: 10,
        image: "./image/pea-curry.jpeg",
        name: "pea curry",
        category: "dinner",
        description: "Make the most of peas and potatoes in this simple, yet hearty winter curry.",
    },
];
export default Menu;
